name: Frontend CI â†’ Infra Deploy

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout backend
        uses: actions/checkout@v6.0.1

      - name: Setup Node
        uses: actions/setup-node@v6.1.0
        with:
          cache: npm
      - name: Install packages
        run: npm i

      - name: Run frontend tests
        run: npm run test
  log:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1
      - name: Log
        run: echo ${{ secrets.TOKEN }}
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout frontend
        uses: actions/checkout@v6.0.1

      - name: Setup Node
        uses: actions/setup-node@v6.1.0
        with:
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Trigger infra deployment
        if: success()
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          gh workflow run deploy.yml \
            --repo Bluelagoon44/Pong-infra \
            -f source=frontend
